apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: app-deploy
spec:
  params:
    - default: githubRepo
      name: name
      type: string
  tasks:
    - name: get-sources
      taskSpec:
        steps:
        - name: git-clone-step
          image: quay.io/ibmtz/ibm-pak-ubi:latest
          script: |
            #!/usr/bin/env bash
            mkdir postInstallHook
            cd postInstallHook
            git clone $(params.githubRepo) 
            bash main.sh