apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: app-deploy
spec:
  params:
    - name: githubRepo
      type: string
  tasks:
    - name: post-install
      taskSpec:
        steps:
        - name: run-post-install
          image: quay.io/ibmtz/ibm-pak-ubi:latest
          script: |
            #!/usr/bin/env bash
            mkdir postInstallHook
            cd postInstallHook
            git clone $(params.githubRepo) 
            bash main.sh