apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: post-install-hook
  namespace: default
spec:
  params:
    - name: githubRepo
      type: string
      default: ""
  tasks:
    - name: post-install
      params:
      - name: githubRepo
        value: "$(params.githubRepo)"
      taskSpec:
        params:
          - name: githubRepo
        steps:
        - name: git-clone-step
          image: quay.io/ibmtz/ibm-pak-ubi:latest
          script: |
            #!/usr/bin/env bash
            mkdir postInstallHook
            cd postInstallHook
            git clone $(params.githubRepo) 
            bash main.sh