apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: post-install-hook
  namespace: default
spec:
  params:
    - name: githubRepo
      type: string
  tasks:
    - name: post-install
      taskRef:
        kind: Task
        name: ibm-pak
      params:
        - name: SCRIPT
          value: |
          script: |
            #!/usr/bin/env bash
            mkdir postInstallHook
            cd postInstallHook
            git clone $(params.githubRepo) 
            bash main.sh